229048_NileshKamble/Iacsd/Models/ErrorViewModel.cs
namespace Iacsd.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

229048_NileshKamble/Iacsd/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Iacsd.Models;

namespace Iacsd.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

229048_NileshKamble/Iacsd/Controllers/IacsdController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Iacsd.Models;
using BLL;
using BOL;

namespace Iacsd.Controllers;

public class IacsdController : Controller
{
    private readonly ILogger<IacsdController> _logger;

    public IacsdController(ILogger<IacsdController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        ViewData["IacsdCourses"]=IacsdManager.GetIacsdCourses();
        return View();
    }

    public IActionResult StudentCourse(int id)
    {
        List<BOL.Iacsd> iacsdCourse =IacsdManager.GetIacsdCourses();
        foreach(BOL.Iacsd course in iacsdCourse){
            if(course.CourseId == id){
                ViewData["StudentByCourse"]=StudentManager.GetIacsdStudentByCourse(course);
            }
        }
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

229048_NileshKamble/Iacsd/Controllers/StudentController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Iacsd.Models;
using BLL;
using BOL;

namespace Iacsd.Controllers;

public class StudentController : Controller
{
    private readonly ILogger<StudentController> _logger;

    public StudentController(ILogger<StudentController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult InsertData(int id, string name, string course, string address)
    {
        Student student = new Student(){Id=id,Name=name,Course=course,Address=address};
        StudentManager.InsertStudentData(student);   
        return Redirect("/Home/Index");
    }

    public IActionResult UpdateData()
    {
        return View();
    }

    public IActionResult UpdateStudentData(string column,int id,string value){
        StudentManager.UpdateStudentData(column,id,value);
        return Redirect("/Home/Index");
    }

    public IActionResult DeleteStudent()
    {
        return View();
    }

    public IActionResult DeleteStudentData(int id){
        StudentManager.DeleteStudentData(id);
        return Redirect("/Home/Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

229048_NileshKamble/Iacsd/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

229048_NileshKamble/Iacsd/Views/Iacsd/Index.cshtml
@using BOL;
@using System.Collections.Generic;
@{
    ViewData["Title"] = "Course Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Iacsd</h1>
    @{
        List<Iacsd> courses = ViewData["IacsdCourses"] as List<Iacsd>;

            <table border="2px">
                <tr><th>Course Id</th><th>Course Name</th><th>Course Building</th></tr>
            @foreach (Iacsd course in courses)
            {
                <tr><td><a href="/Iacsd/StudentCourse/@course.CourseId">@course.CourseId</a></td><td>@course.CourseName</td><td>@course.CourseBldg</td></tr>
            }
            </table>
    }
</div>

229048_NileshKamble/Iacsd/Views/Iacsd/StudentCourse.cshtml
@using BOL;
@using System.Collections.Generic;
@{
    ViewData["Title"] = "Course Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Iacsd</h1>
    @{
        List<Student> students = ViewData["StudentByCourse"] as List<Student>;

            <table border="2px">
                <tr><th>Student Id</th><th>Student Name</th><th>Student Course</th><th>Student Address</th></tr>
            @foreach (Student student in students)
            {
                <tr><td>@student.Id</td><td>@student.Name</td><td>@student.Course</td><td>@student.Address</td></tr>
            }
            </table>
    }
</div>

229048_NileshKamble/Iacsd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Iacsd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Iacsd.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Iacsd</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Iacsd" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="UpdateData">Update Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="DeleteStudent">Delete Student Data</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Iacsd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

229048_NileshKamble/Iacsd/Views/Student/DeleteStudent.cshtml
@{
    ViewData["Title"] = "Update Student Data Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <form action="/Student/DeleteStudentData" method="post">
        <div>Enter Student Id : <input type="number" name="id"></input></div>
        <button type="submit">Submit</button>
    </form>
</div>

229048_NileshKamble/Iacsd/Views/Student/Index.cshtml
@{
    ViewData["Title"] = "Student Registration Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <form action="/Student/InsertData" method="post">
        <div>Student Id : <input type="number" name="id"></input></div>
        <div>Student Name : <input type="text" name="name"></input></div>
        <div>Student Course : <input type="text" name="course"></input></div>
        <div>Student Address : <input type="text" name="address"></input></div>
        <button type="submit">Submit</button>
    </form>
</div>

229048_NileshKamble/Iacsd/Views/Student/UpdateData.cshtml
@{
    ViewData["Title"] = "Update Student Data Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <form action="/Student/UpdateStudentData" method="post">
        <div>
            <h4>Select The data to be updated</h4>
            @* <input type="radio" name="Column" value="Id">Student Id</input> *@
            <input type="radio" name="Column" value="Name">Student Name</input>
            <input type="radio" name="Column" value="Course">Student Course</input>
            <input type="radio" name="Column" value="Address">Student Address</input>
        </div>
        <div>Enter Student Id : <input type="number" name="id"></input></div>
        <div>Enter Value :<input type="text" name="value"></input></div>
        <button type="submit">Submit</button>
    </form>
</div>